### ISSUE TITLE
Repository Issue

### ISSUE THREAD

**Issue by leoheck** [vooze/arc-darker-ubuntu#8]
Hi @vooze, 

I would like to know why you created a new repository instead of making a fork of the arc? I don't know but I think that a fork could be easy to merge the new arc changes.

Actually, I think you should add stuff to arc project instead of a create a new one. I like arc because the developer keeps it regularly updated, which is a hard task. And he is very friendly, instead of other developers.

For example, he added in its arc repository, my [arc-theme-script](https://github.com/horst3180/arc-theme/blob/master/arc-theme-upgrade) proposal to upgrade it easy from the command line, like this:

``` bash
sudo arc-theme-upgrade
```

I think your modifications are really good:
- dark menus (I am waiting for it for a long time ago)
- lightdm theme 
- osx icons (actually, this feature is not for me)
- new colors

We can change this repository to be a customization of the arc theme. So, I think the user should install arc from its repository, then apply this repository to make it fit better to its needs. 

For example, I still want to change nautilus sidebar to:
- Reduce the size between items
- Add separation lines (as in ambiance theme for example) 

We can add some options fo arc here, what do you think about that?
Maybe if it becomes good we can add this to arc repository itself. 

Well, this is only a simple suggestion to make awesome things :)

**Comment by vooze** [comment]
@leoheck 

For making a fork, that would mean I had to manage GTK 3.14-3.20. I will only manage what I'm using myself, which is Ubuntu LTS. So it was much easier for me to do it this way. If I had to support all GTK versions it would be really time consuming for me.

This is probably the last GTK versions i'll support, since I'm moving to ubuntu 18.04 next time, which I suspect will use Unity8 + QT.

For ubuntu 14.04 I used https://github.com/anmoljagetia/Flatabulous and made many local customizations for myself, but this time, I decided to use Arc and publish it, just to be nice :) - I'm not a CSS coder or anything.

This is also my first ever repository on github, and I'm really new to forking, pull requests etc. - As much as anything this is mostly a learning experience for me.

Hope you understand.

I might look into the the separation lines when I have some time :)

**Comment by vooze** [comment]
@leoheck I have now added separators for menus and nautilus. Hope you like it.
I'm still not sure if I want less space in nautilus sidebar (if I understand correctly you would like that?)

**Comment by leoheck** [comment]
Sure I understand, I am actually kinda new here too :)

Discussing nautilus, [my post](https://github.com/horst3180/arc-theme/issues/298) in arc issues shows what I am expecting. Look in the first image. The nautilus sidebar has little less whitespace between its items in the Ambiance theme. Look the "trash" entry for example... In arc, it is almost 1cm shifted to bottom. I would like to have that consuming less space, as the original nautilus.

I have one last comment about the menu colors... You increased the contrast for disabled-text that was pretty good. However, the enabled-text still huts the eyes. Do you use bold font there? I think that the arc-dark can give you a good color/style for that. What do you think?

**Comment by vooze** [comment]
@leoheck It's not bold, it's just 100% dark (#000000) I personally like that. I hate the font-color from original arc, it's way to light, in my opinion.

**Comment by vooze** [comment]
@leoheck Also, I looked into it, and can't figure out what part of the gtk.css that is related to "Reduce the size between items" if you know, please let me know.

**Comment by leoheck** [comment]
This is thing hard to find. Its possible to compare with ~~numix~~ or ambiance themes.. I will try to find something related.

Edited: Numix has the same margin/padding around items

**Comment by vooze** [comment]
Yeah I looked at Ambiance but could not find it. It's not really important for me. Closing until we know more.
